# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn lerna bootstrap
    - run: yarn build
    - shell: bash
      # update locally with:
      # openssl aes-256-cbc -e -in ~/.clasprc.json -out ./.clasprc.json.enc -k $KEY
      run: openssl aes-256-cbc -d -in .clasprc.json.enc -k $KEY > $HOME/.clasprc.json
      env:
        KEY: ${{ secrets.KEY }}
    - shell: bash
      # update locally with:
      # openssl aes-256-cbc -e -in ./backend/gas-test-credentials.json -out ./backend/gas-test-credentials.json.enc -k $KEY
      run: openssl aes-256-cbc -d -in ./backend/gas-test-credentials.json.enc -k $KEY > ./backend/gas-test-credentials.json
      env:
        KEY: ${{ secrets.KEY }}
    - run: yarn test
      env:
        CI: true
